name: petcare_flutter_pro
description: "Pet Care Management Flutter Web Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  google_fonts: ^9.0.0
  intl: ^0.20.3
  flutter_animate: ^4.5.2
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true